# pepper_robot Travis Continuous Integration Configuration File
# Author: Yuki Furuta <furushchev@jsk.imi.i.u-tokyo.ac.jp>
language: generic
dist: trusty
# notifications:
#   email:
#     recipients: vincent.rabaud@gmail.com
#     on_success: change #[always|never|change] # default: change
#     on_failure: change #[always|never|change] # default: always
env:
  - ROS_DISTRO=indigo
  - ROS_DISTRO=jade
before_install: # Use this to prepare the system to install prerequisites or dependencies
  - export DEBIAN_FRONTEND=noninteractive
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c "echo \"deb http://packages.ros.org/ros-shadow-fixed/ubuntu `lsb_release -sc` main\" > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-catkin-tools python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros
  - sudo -H pip install -U pip
  - sudo -H pip install -U catkin_pkg
install: # Use this to install any prerequisites or dependencies necessary to run your build
  # Create workspace
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace
  - cd ../
  # Install dependencies for source repos
  - sudo rosdep init
  - ret=1
  - rosdep update || while [ $ret != 0 ]; do sleep 1; rosdep update && ret=0 || echo "failed"; done
  - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -r -n -y
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - catkin build --continue-on-failure
  - catkin run_tests --continue-on-failure
  - catkin_test_results build
